### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by neurohn** [HyeonwooNoh/caffe#1]
Hi,

I'm noticing the following errors while trying to install your version of caffe:
$ make all-j8
Normal output barring this warning:
"src/caffe/layers/unpooling_layer.cu(100): warning: variable "pool_size" was declared but never referenced
detected during instantiation of "void caffe::UnpoolingLayer<Dtype>::Forward_gpu(const std::vectorcaffe::Blob<Dtype *, std::allocatorcaffe::Blob<Dtype *>> &, const std::vectorcaffe::Blob<Dtype *, std::allocatorcaffe::Blob<Dtype *>> &) [with Dtype=float]"
(290): here

src/caffe/layers/unpooling_layer.cu(100): warning: variable "pool_size" was declared but never referenced
detected during instantiation of "void caffe::UnpoolingLayer<Dtype>::Forward_gpu(const std::vectorcaffe::Blob<Dtype *, std::allocatorcaffe::Blob<Dtype *>> &, const std::vectorcaffe::Blob<Dtype *, std::allocatorcaffe::Blob<Dtype *>> &) [with Dtype=float]"
(290): here

src/caffe/layers/unpooling_layer.cu(100): warning: variable "pool_size" was declared but never referenced
detected during instantiation of "void caffe::UnpoolingLayer<Dtype>::Forward_gpu(const std::vectorcaffe::Blob<Dtype *, std::allocatorcaffe::Blob<Dtype *>> &, const std::vectorcaffe::Blob<Dtype *, std::allocatorcaffe::Blob<Dtype *>> &) [with Dtype=float]"
(290): here

src/caffe/layers/unpooling_layer.cu(100): warning: variable "pool_size" was declared but never referenced

src/caffe/layers/unpooling_layer.cu(100): warning: variable "pool_size" was declared but never referenced

src/caffe/layers/unpooling_layer.cu(100): warning: variable "pool_size" was declared but never referenced"

$ make test
Normal

$ make runtest
"src/caffe/test/test_math_functions.cpp:202: Failure
Value of: x[i] > 0 ? x[i] : -x[i]
  Actual: 0.233989
Expected: abs_val[i]
Which is: 0"
[  FAILED  ] MathFunctionsTest/1.TestFabsGPU, where TypeParam = double (33444 ms)

Kindly let me know whats wrong here. Any help will be appreciated.

**Comment by neurohn** [comment]
Forgot to uncomment the lines in Makefile.config for CUDA>6.0. Maybe this could be mentioned in the README.

**Comment by HyeonwooNoh** [comment]
I see. Thanks for the suggestion!
