### ISSUE TITLE
Erros in 'make all'

### ISSUE THREAD

**Issue by resemin** [HyeonwooNoh/caffe#10]
I'm try to build (make all) this code  with Ubuntu 14.04, cuda-7.5, cudnn-v4, Titan X.
But, I got belows messages.
In my case, this code was only success without USE_CUDNN.
Also, There was no problem with the newest original code of caffe.
Doesn't this code work with USE_CUDNN?
Please help me.

sm5@sv:~/caffe-master$ make all
PROTOC src/caffe/proto/caffe.proto
PROTOC src/caffe/proto/caffe_pretty_print.proto
CXX .build_release/src/caffe/proto/caffe.pb.cc
CXX .build_release/src/caffe/proto/caffe_pretty_print.pb.cc
CXX src/caffe/solver.cpp
In file included from ./include/caffe/util/device_alternate.hpp:40:0,
                 from ./include/caffe/common.hpp:18,
                 from ./include/caffe/blob.hpp:4,
                 from ./include/caffe/net.hpp:10,
                 from src/caffe/solver.cpp:7:
./include/caffe/util/cudnn.hpp:60:32: error: variable or field ‘createTensor4dDesc’ declared void
 inline void createTensor4dDesc(cudnnTensor4dDescriptor_t\* desc) {
                                ^
./include/caffe/util/cudnn.hpp:60:32: error: ‘cudnnTensor4dDescriptor_t’ was not declared in this scope
./include/caffe/util/cudnn.hpp:60:59: error: ‘desc’ was not declared in this scope

...
...
...

./include/caffe/util/cudnn.hpp:113:13: error: ‘CUDNN_POOLING_AVERAGE’ was not declared in this scope
     *mode = CUDNN_POOLING_AVERAGE;
             ^
./include/caffe/util/cudnn.hpp:120:27: error: there are no arguments to ‘cudnnSetPoolingDescriptor’ that depend on a template parameter, so a declaration of ‘cudnnSetPoolingDescriptor’ must be available [-fpermissive]
         stride_h, stride_w));
                           ^
./include/caffe/util/cudnn.hpp:12:28: note: in definition of macro ‘CUDNN_CHECK’
     cudnnStatus_t status = condition; \

**Comment by gadkins** [comment]
I had the same issue. Check out my answer here: #9

**Comment by resemin** [comment]
gadkins/ Thank you very much! It works~!
