### ISSUE TITLE
I am having cudasuccess error

### ISSUE THREAD

**Issue by lolongcovas** [HyeonwooNoh/caffe#2]
I am trying to do convolutional autoencoders and I've got this error: cudaSuccess (8 vs. 0)  invalid device function 

my card is gtx 960 and it has cuda capabilities. do u know why?

**Comment by HyeonwooNoh** [comment]
I couldn't figure out the reason by looking the error type only. 
Could you elaborate more?

**Comment by lolongcovas** [comment]
Hi,

finally I copied ur code into caffe master branch and clean a bit (uppercase layer definition). now it works! thanks any way
