### ISSUE TITLE
Multinomial Logistical Loss

### ISSUE THREAD

**Issue by affromero** [HyeonwooNoh/caffe#6]
Is there any chance to use MultinomialLogisticalLossLayer for this architecture?

My problem relies on I have tiny objects to classify in each image and using softmaxlayer, the network always "learn" to predict background label, which indeed is around 95% of the image. My problem does not admit edge-boxes extracting object proposals. Someone advice me to use logistic loss.

**Comment by HyeonwooNoh** [comment]
Did you mean using SigmoidCrossEntropyLoss?
I guess using MultinomialLogisticLoss doesn't help since this loss layer is equal to softmaxlayer except that the input have to have probability distribution already.
Note that "SoftmaxLayer + MultinomialLogisticLossLyaer" is equal to "SoftmaxLossLayer".
