### ISSUE TITLE
Unable to build with cuDNN flag

### ISSUE THREAD

**Issue by gadkins** [HyeonwooNoh/caffe#9]
I've tried using cudnn versions 2, 3 & 4, none of which work.
I have no problems making on the master caffe with USE_CUDNN := 1, however, when I try to make this branch of caffe, I get the following errors:

make: **\* [.build_release/src/caffe/lmdb_dataset.o] Error 1
In file included from ./include/caffe/util/device_alternate.hpp:40:0,
                 from ./include/caffe/common.hpp:18,
                 from ./include/caffe/internal_thread.hpp:4,
                 from src/caffe/internal_thread.cpp:1:
./include/caffe/util/cudnn.hpp:60:32: error: variable or field ‘createTensor4dDesc’ declared void
 inline void createTensor4dDesc(cudnnTensor4dDescriptor_t\* desc) {
                                ^
./include/caffe/util/cudnn.hpp:60:32: error: ‘cudnnTensor4dDescriptor_t’ was not declared in this scope
./include/caffe/util/cudnn.hpp:60:59: error: ‘desc’ was not declared in this scope
 inline void createTensor4dDesc(cudnnTensor4dDescriptor_t\* desc) {
                                                           ^
./include/caffe/util/cudnn.hpp:65:29: error: variable or field ‘setTensor4dDesc’ declared void
 inline void setTensor4dDesc(cudnnTensor4dDescriptor_t\* desc,
                             ^
./include/caffe/util/cudnn.hpp:65:29: error: ‘cudnnTensor4dDescriptor_t’ was not declared in this scope
./include/caffe/util/cudnn.hpp:65:56: error: ‘desc’ was not declared in this scope
 inline void setTensor4dDesc(cudnnTensor4dDescriptor_t\* desc,
                                                        ^
... etc.

Any suggestions as to what might be causing this?

**Comment by gadkins** [comment]
I was able to fix this problem by using cuDNN v1 cudnn.h file. Turns out this branch of caffe is using "cudnnTensor4dDescriptor_t\* desc" in include/caffe/util/cudnn.hpp while the master uses "cudnnTensorDescriptor_t\* desc". Additionally cuDNN v1 uses "cudnnTensor4dDescriptor_t\* desc" in the cudnn.h file whereas cuDNN v2, v3 and v4 use "cudnnTensorDescriptor_t\* desc". Basically you need to make sure your pointer in cudnn.h matches your pointer in cudnn.hpp.

**Comment by saviogeorge** [comment]
Yes what @gadkins has mentioned is right I had the same issue and i got it working by replacing the cudNN(from version 5 to version 1).

Such errors are common and basically the problem will be linked to the mismatch in the cuDNN version. So by getting and compiling with the right version of of cuDNN should solve the problem
